// Generated by Wrangler by running `wrangler types`

interface Env {
	LATEST_SCORE: KVNamespace;
	OSU_API_V2_CLIENT_ID: string;
	OSU_API_V2_CLIENT_SECRET: string;
	DISCORD_WEBHOOK_URL: string;
	FARMATHON_TIMER_LINKSHARE: string;
}
